#!/bin/bash

declare -i DEBUG=0
ROOT_DIR=$(cd "$(dirname $0)" && pwd)
TMP=/tmp/app
mkdir -p $ROOT_DIR/logs  $ROOT_DIR/db/beanstalkd $ROOT_DIR/db/redis $TMP
# $ROOT_DIR/tmp

source $ROOT_DIR/bin/shell_func.sh

case "$1" in

_updateconf)
	updateConfigs
	exit 0
	;;
_update)
	updateConfigs
	/usr/local/openresty/nginx/sbin/nginx -p $ROOT_DIR -c $TMP/nginx.conf -s reload
	exit 0
	;;
redis)
	shift
	/usr/bin/redis-cli -s $TMP/redis.sock $@
	exit 0
	;;
nginx)
	shift
	/usr/local/openresty/nginx/sbin/nginx -p $ROOT_DIR -c $TMP/nginx.conf $@
	exit $?
	;;
esac
updateConfigs
$ROOT_DIR/bin/python_env/gbc/bin/supervisorctl -c $TMP/supervisord.conf $@
# $ROOT_DIR/bin/python_env/gbc/bin/supervisorctl -c $ROOT_DIR/tmp/supervisord.conf $@
